
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nitin
 */
public class Actions extends javax.swing.JFrame {

    /**
     * Creates new form Actions
     */
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement  pst = null;
    public Actions() {
        initComponents();
        setLocationRelativeTo(null);
        conn = Javaconnect.dbConnector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ResetVoting = new javax.swing.JButton();
        AddVoter = new javax.swing.JButton();
        CandidateUpdate = new javax.swing.JButton();
        CheckResults = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ResetVoting.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        ResetVoting.setText("RESET VOTING");
        ResetVoting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetVotingActionPerformed(evt);
            }
        });

        AddVoter.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        AddVoter.setText("Voter details");
        AddVoter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVoterActionPerformed(evt);
            }
        });

        CandidateUpdate.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        CandidateUpdate.setText("Candidate Details");
        CandidateUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CandidateUpdateActionPerformed(evt);
            }
        });

        CheckResults.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        CheckResults.setText("CHECK RESULTS");
        CheckResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckResultsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ResetVoting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CandidateUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(AddVoter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CheckResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ResetVoting, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CandidateUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddVoter, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(CheckResults, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("WELCOME ADMIN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckResultsActionPerformed
        new CheckResults().setVisible(true);
        dispose();
    }//GEN-LAST:event_CheckResultsActionPerformed

    private void ResetVotingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetVotingActionPerformed
        int res = JOptionPane.showConfirmDialog(null,"Are you sure you want to reset voting");
        if(res == JOptionPane.YES_OPTION)
        {
            String sql = "select * from VoterId where Flag=1";
            try
            {
                pst =  conn.prepareStatement(sql);
                rs = pst.executeQuery();
                while(rs.next())
                {
                    String name = rs.getString("Name");
                    String sql1 = "update VoterId set Flag='"+0+"' where Name='"+name+"' ";
                    pst = conn.prepareStatement(sql1);
                    pst.execute();
                }
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            String query = "select * from CandidateList where Votes>0";
            try
            {
                pst =  conn.prepareStatement(query);
                rs = pst.executeQuery();
                while(rs.next())
                {
                    String name = rs.getString("Name");
                    String sql1 = "update CandidateList set Votes='"+0+"',VotePercentage='"+0+"' where Name='"+name+"' ";
                    pst = conn.prepareStatement(sql1);
                    pst.execute();
                }
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_ResetVotingActionPerformed

    private void CandidateUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CandidateUpdateActionPerformed
        // TODO add your handling code here:
        UpdateDetails up = new UpdateDetails();
        up.setVisible(true);
        dispose();
    }//GEN-LAST:event_CandidateUpdateActionPerformed

    private void AddVoterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVoterActionPerformed
        // TODO add your handling code here:
        updateVoter uv = new updateVoter();
        uv.setVisible(true);
        dispose();
    }//GEN-LAST:event_AddVoterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Actions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddVoter;
    private javax.swing.JButton CandidateUpdate;
    private javax.swing.JButton CheckResults;
    private javax.swing.JButton ResetVoting;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
