/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ravi chan
 */
public class Login extends javax.swing.JFrame {

    Connection conn = null;
    private JFrame JF = this; 
    ResultSet rs = null;
    PreparedStatement  pst = null;
    public Login() {
        initComponents();
        setSize(800,600);
        setLocationRelativeTo(null);
        conn = Javaconnect.dbConnector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Voterid = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        loginbutton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("VoterId");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 180, 59, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 220, 74, 22);

        Voterid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Voterid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoteridActionPerformed(evt);
            }
        });
        getContentPane().add(Voterid);
        Voterid.setBounds(440, 180, 190, 30);

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(440, 220, 190, 30);

        loginbutton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        loginbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nitin\\Desktop\\ok.png")); // NOI18N
        loginbutton.setText("Login");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(loginbutton);
        loginbutton.setBounds(454, 282, 117, 41);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 430, 61, 25);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nitin\\Desktop\\OOM PROJECT\\Images\\Users-icon.png")); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 150, 260, 170);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoteridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoteridActionPerformed
        
    }//GEN-LAST:event_VoteridActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        int count = 0;
        int count1 = 0;
        try
           {
                String query = "select * from VoterId where VoterId=? and Password=?";
                pst =  conn.prepareStatement(query);
                pst.setString(1,Voterid.getText());
                pst.setString(2,password.getText());
                rs = pst.executeQuery();
                while(rs.next())
                {
                    count1=1;
                    if(rs.getInt("Flag")==1)
                    {
                        JOptionPane.showMessageDialog(null, "Already Voted");
                        count =1;
                    }
                }
                if(count1==0)
                {
                    JOptionPane.showMessageDialog(null, "Username and password is incorrect");
                }
           }
           catch(Exception e)
           {
               JOptionPane.showMessageDialog(rootPane, e);
           }
        if(count1==1&&count==0)
        {
        String sql = "select * from VoterId where VoterId=?";
        try 
        {
            pst =  conn.prepareStatement(sql);
            pst.setString(1,Voterid.getText());
            rs = pst.executeQuery();
            if(rs.next())
            {
                //JOptionPane.showMessageDialog(null, "Logged in Sucessfully");
                String sql1 = "update VoterId set Flag='"+1+"' where VoterId='"+Voterid.getText()+"' ";
                pst.close();
                pst =  conn.prepareStatement(sql1);
                pst.execute();
                pst.close();
                VoteForParty vfp = new VoteForParty();
                vfp.setVisible(true);
                this.setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Username and password is incorrect");
            }
        } 
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        }
        else
        {
            Voterid.setText("");
            password.setText("");
        }
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        Welcome welcome = new Welcome();
        welcome.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Voterid;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginbutton;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables
}
